# Generated by Django 2.2 on 2019-11-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Clothing'), ('E', 'Electronics'), ('F', 'Furnitures')], max_length=2),
        ),
    ]
